### PR TITLE
Bugfix - Issue #423 - Phone number validation consistency

### LINKED ISSUE #423: Bug: iconsistent Phone number validation
**Describe the bug**
Phone number validation differ between various company details forms (i.e. registration, content moderator edit)

**To Reproduce**
1. Register as a new Company rep, add a NL phone number, it validates
2. As an event organizer, edit the company details
3. Do not change phone number
4. On save: See error

**Expected behavior**
All phone number inputs should validate consistently

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by v-stamenova**
# Description

This branch introduces a phone number validation in the crew page as well as removing the required field from the phone as per feedback from the demo

closes #423 

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## What needs to be tested

- [ ] Register as company and test that it's optional, but if it's present the validation work
- [ ] The same but as logged in moderator trying to add a company

# Checklist:

- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by TimKardol — APPROVED** [review]

File: app/Actions/Fortify/CreateNewUser.php [hunk 1]
```diff
@@ -36,7 +36,7 @@ public function create(array $input): User
                 'company_name' => 'required',
                 'company_description' => 'required',
                 'company_website' => 'required',
-                'company_phone_number' => ['required', 'phone:INTERNATIONAL,NL'],
+                'company_phone_number' => ['phone:INTERNATIONAL,NL'],
```
Comment (dwaard) [inline app/Actions/Fortify/CreateNewUser.php:39]: For the sake of "consistency": `nullable` or not?
